# Generated by Django 2.0.4 on 2018-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '考试管理', 'verbose_name_plural': '考试管理'},
        ),
        migrations.AlterModelOptions(
            name='examlog',
            options={'verbose_name': '考试记录', 'verbose_name_plural': '考试记录'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '问题管理', 'verbose_name_plural': '问题管理'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': '提交记录', 'verbose_name_plural': '提交记录'},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(verbose_name='答案编号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(max_length=500, verbose_name='选项1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(max_length=500, verbose_name='选项2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(max_length=500, verbose_name='选项3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.CharField(max_length=500, verbose_name='选项4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='所属病种'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=2, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.CharField(default='暂无解析', max_length=500, verbose_name='答案解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='问题描述'),
        ),
    ]
