# Generated by Django 2.0.4 on 2018-04-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20180415_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '测试管理', 'verbose_name_plural': '测试管理'},
        ),
        migrations.AlterModelOptions(
            name='examhasquestion',
            options={'verbose_name': '考题管理', 'verbose_name_plural': '考题管理'},
        ),
        migrations.RemoveField(
            model_name='examhasquestion',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='examhasquestion',
            name='question_id',
        ),
        migrations.AddField(
            model_name='examhasquestion',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examhasquestion',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.Question'),
            preserve_default=False,
        ),
    ]
