# Generated by Django 2.0.4 on 2018-04-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20180415_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '试卷信息维护', 'verbose_name_plural': '试卷信息维护'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '题库管理', 'verbose_name_plural': '题库管理'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='试卷作者'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.CharField(max_length=500, verbose_name='试卷名称'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pubdate',
            field=models.DateTimeField(verbose_name='公开日期'),
        ),
        migrations.AlterField(
            model_name='examhasquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='试卷名称'),
        ),
        migrations.AlterField(
            model_name='examhasquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='score',
            field=models.IntegerField(verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='examlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='choice',
            field=models.IntegerField(verbose_name='选择答案'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question', verbose_name='问题编号'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='提交编号'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
