# Generated by Django 2.0.4 on 2018-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20180418_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='考试时间'),
        ),
    ]
