# Generated by Django 2.0.4 on 2018-04-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(verbose_name='提交日期'),
        ),
    ]
