# Generated by Django 2.0.4 on 2018-04-25 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20180419_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 23, 59, 59), verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question', verbose_name='问题描述'),
        ),
    ]
