# Generated by Django 2.0.4 on 2018-04-26 01:24

import disease.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='病种名称')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='文字描述')),
                ('videoUrl', models.FileField(blank=True, null=True, upload_to=disease.utilities.scramble_video_filename, verbose_name='示例视频')),
            ],
            options={
                'verbose_name': '病例信息管理',
                'verbose_name_plural': '病例信息管理',
            },
        ),
        migrations.CreateModel(
            name='DiseaseGroup',
            fields=[
                ('dgid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='疾病科目名')),
            ],
            options={
                'verbose_name': '疾病科目管理',
                'verbose_name_plural': '疾病科目管理',
            },
        ),
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片描述')),
                ('image', models.ImageField(upload_to=disease.utilities.scramble_uploaded_filename, verbose_name='病例图片')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.Disease', verbose_name='病例名称')),
            ],
            options={
                'verbose_name': '病例图片管理',
                'verbose_name_plural': '病例图片管理',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='阶段说明')),
                ('image', models.ImageField(blank=True, null=True, upload_to=disease.utilities.scramble_uploaded_filename, verbose_name='图片描述')),
                ('phase', models.IntegerField(default=1, verbose_name='病情所属阶段')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.Disease', verbose_name='疾病名称')),
            ],
            options={
                'verbose_name': '疾病流程管理',
                'verbose_name_plural': '疾病流程管理',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.DiseaseGroup', verbose_name='所属科目'),
        ),
    ]
