# Generated by Django 2.0.4 on 2018-04-26 00:40

from django.db import migrations, models
import room.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='科室名称')),
                ('description', models.CharField(max_length=2000, verbose_name='科室介绍')),
                ('image', models.ImageField(blank=True, null=True, upload_to=room.utilities.scramble_uploaded_filename, verbose_name='科室图片')),
            ],
        ),
    ]
