# Generated by Django 2.0.4 on 2018-04-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200, verbose_name='科室名称')),
                ('dialog', models.CharField(max_length=20000, verbose_name='角色扮演对话内容')),
            ],
            options={
                'verbose_name': '角色对话内容',
                'verbose_name_plural': '角色对话内容',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '科室信息维护', 'verbose_name_plural': '科室信息维护'},
        ),
    ]
