# Generated by Django 2.0.4 on 2018-04-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20180426_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': '科室学习对话内容', 'verbose_name_plural': '科室学习对话内容'},
        ),
    ]
